kind: Service
apiVersion: v1
metadata:
  name: mcs-ping-pong-master
  namespace: istio-test
  labels:
    app: mcs-ping-pong-master
  annotations:
    kubesphere.io/creator: ferdinandsu
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: mcs-ping-pong-master
  clusterIP: None
  type: ClusterIP
  sessionAffinity: None
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: mcs-ping-pong-master
  namespace: istio-test
  labels:
    app: mcs-ping-pong-master
  annotations:
    deployment.kubernetes.io/revision: "3"
    kubesphere.io/creator: ferdinandsu
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mcs-ping-pong-master
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mcs-ping-pong-master
      annotations:
        kubesphere.io/creator: ferdinandsu
        kubesphere.io/imagepullsecrets: "{}"
        kubesphere.io/restartedAt: "2023-05-16T05:58:26.874Z"
    spec:
      containers:
        - name: mcs-ping-pong
          image: "192.168.1.104:5000/cloud-collaboration-platform/mcs-ping-pong:0.2"
          ports:
            - name: tcp-80
              containerPort: 80
              protocol: TCP
          env:
            - name: APP_URL
              value: "http://mcs-ping-pong-master/"
            - name: INSTANCE_ID
              value: "master"
          resources: {}
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      dnsPolicy: ClusterFirst
